import 'dart:async';
import 'dart:math';

import 'package:flutter/widgets.dart';
import 'package:flutter_soloud/flutter_soloud.dart';

import 'audio_taper.dart';

/// Looping ambient background music as a SHUFFLED, CROSSFADING playlist of
/// several short beds (assets/audio/music_calm_*.ogg, generated by
/// tool/generate_music.py).
///
/// Backed by **SoLoud** (`flutter_soloud`). Each bed streams from disk (low
/// RAM), and crossfades/ducks use SoLoud's **native per-voice `fadeVolume`**.
/// This replaces the old `audioplayers` path that ramped volume from a Dart
/// `Timer.periodic`, hammering the platform channel tens of times a second —
/// the "zipper" that read as a random click/crackle in the music. Native fades
/// run on the audio thread, so the bed glides cleanly with no discontinuities.
///
/// Two tracks overlap during a crossfade (both resolve to silence at their
/// edges, so it is a true crossfade, never an audible loop). Starts after
/// launch — or on the first tap where autoplay is restricted (web) — pauses
/// with the app lifecycle, and is gated by the user's "Music" setting.
class MusicService with WidgetsBindingObserver {
  MusicService({required this.isEnabled});

  final bool Function() isEnabled;

  // Lazily resolved so constructing the service never loads SoLoud's native
  // library — the test fakes extend this class but never call initialize, so in
  // the plain Dart VM (no .so) the engine is simply never touched.
  late final SoLoud _soloud = SoLoud.instance;

  /// The shuffled-once-through playlist of bed assets (full asset keys).
  static const List<String> _tracks = [
    'assets/audio/music_calm_1.ogg',
    'assets/audio/music_calm_2.ogg',
    'assets/audio/music_calm_3.ogg',
    'assets/audio/music_calm_4.ogg',
    'assets/audio/music_calm_5.ogg',
    'assets/audio/music_calm_6.ogg',
  ];

  /// How long one track overlaps the next. Both tracks resolve to silence at
  /// their edges, so the overlap is a true crossfade, not a duck.
  static const Duration _crossfade = Duration(milliseconds: 5000);

  /// Used only if a track's real duration can't be read from the decoder
  /// (rare). Shorter than the shortest generated track (72 s) so the crossfade
  /// always starts before the track ends rather than after.
  static const Duration _fallbackDuration = Duration(seconds: 66);

  /// The bed's base level at full user volume; the mastered tracks are
  /// loudness-matched, so full player volume gives a present bed, not a whisper.
  static const double _baseVolume = 1.0;

  /// Fraction of the playing level the bed dips to under the success fanfare.
  /// Deliberately not near-zero: the fanfare rides *over* the bed.
  static const double _duckFactor = 0.38;

  /// 0..1 user multiplier from settings (musicVolume). Mirrors the AppSettings
  /// default (0.65) until the persisted value is applied at startup.
  double _userVolume = 0.65;

  double get _targetVolume => (_baseVolume * _userVolume).clamp(0.0, 1.0);
  double get _duckVolume => _targetVolume * _duckFactor;

  /// Beds decoded/opened once, keyed by track index. Disk mode keeps them
  /// streaming (low RAM) rather than fully decoded into memory.
  final Map<int, AudioSource> _sources = {};

  /// The foreground voice and (only during a crossfade) the incoming voice.
  SoundHandle? _active;
  SoundHandle? _incoming;
  int _activeIndex = -1;
  int _incomingIndex = -1;

  /// Shuffle bag: track indices not yet played this cycle (no repeat until all
  /// have played, then it reshuffles).
  final List<int> _bag = [];
  final Random _rng = Random();
  int _lastPlayed = -1;

  bool _ready = false;
  bool _started = false; // a track has been started on the active voice
  bool _playing = false; // currently sounding (not paused by toggle/lifecycle)

  Timer? _crossfadeTimer; // schedules the START, then the END, of a crossfade
  Timer? _duckTimer; // restores the bed after a success-fanfare duck
  Timer? _pauseTimer; // pauses voices after a fade-out completes

  /// Applies the user's music-volume preference (0..1). Fades smoothly to the
  /// new level if the bed is currently playing.
  void setUserVolume(double value) {
    // Perceptual taper (shared with SoundService).
    _userVolume = audioTaper(value);
    if (_playing && isEnabled() && _active != null) {
      _fade(_active!, _targetVolume, const Duration(milliseconds: 280));
    }
  }

  Future<void> initialize() async {
    if (_ready) return;
    try {
      // The SoLoud engine is shared with SoundService; init is a no-op if the
      // other service already brought it up.
      if (!_soloud.isInitialized) {
        await _soloud.init();
      }
      for (var i = 0; i < _tracks.length; i++) {
        _sources[i] = await _soloud.loadAsset(_tracks[i], mode: LoadMode.disk);
      }
      _ready = true;
    } catch (_) {
      // Audio is never worth crashing over: stay silent instead.
      _ready = false;
    }
  }

  /// Next track index from the shuffle bag, refilling (and avoiding an
  /// immediate repeat across cycles) when it empties.
  int _nextTrack() {
    if (_bag.isEmpty) {
      final last = _lastPlayed;
      _bag.addAll(List.generate(_tracks.length, (i) => i));
      _bag.shuffle(_rng);
      if (_bag.length > 1 && _bag.first == last) {
        _bag.add(_bag.removeAt(0));
      }
    }
    final idx = _bag.removeAt(0);
    _lastPlayed = idx;
    return idx;
  }

  /// Starts the playlist if it should play and isn't playing yet. Safe to call
  /// often: browsers reject autoplay until the first user gesture, so the app
  /// retries from a global tap listener until one attempt sticks.
  void ensureStarted() {
    if (!isEnabled()) return;
    if (!_ready) {
      _ensureInit(); // self-heal a failed/cold init; retry start when it lands
      return;
    }
    if (_started) return;
    _started = true;
    _playing = true; // optimistic; reverted if the play attempt is rejected
    _startTrack(_nextTrack());
  }

  bool _initRetrying = false;

  /// Self-heals a failed/cold engine: ensureStarted is called on every pointer
  /// down (app.dart), so if the one-shot startup init failed we kick a single
  /// re-init in the background and start once it succeeds — instead of the bed
  /// staying silent forever. Guarded so only one retry is ever in flight.
  void _ensureInit() {
    if (_ready || _initRetrying) return;
    _initRetrying = true;
    initialize().whenComplete(() {
      _initRetrying = false;
      ensureStarted();
    });
  }

  void _startTrack(int index) {
    _crossfadeTimer?.cancel();
    final src = _sources[index];
    if (src == null) {
      _playing = false;
      _started = false;
      return;
    }
    try {
      // Begin silent and fade up natively, so the bed eases in rather than
      // snapping to full level.
      final h = _soloud.play(src, volume: 0, looping: false);
      _active = h;
      _activeIndex = index;
      _incoming = null;
      _fade(h, _targetVolume, const Duration(milliseconds: 900));
      _scheduleCrossfade(src);
    } catch (_) {
      _playing = false;
      _started = false;
    }
  }

  /// Reads the active track's real length and arms the timer that begins the
  /// crossfade [_crossfade] before it ends.
  void _scheduleCrossfade(AudioSource src) {
    _crossfadeTimer?.cancel();
    var total = _safeLength(src);
    var lead = total - _crossfade;
    if (lead < const Duration(seconds: 1)) lead = const Duration(seconds: 1);
    _crossfadeTimer = Timer(lead, _beginCrossfade);
  }

  /// Begins the crossfade: starts the next track silent on a second voice and
  /// fades the two past each other natively, then swaps when done.
  void _beginCrossfade() {
    if (!_ready || !_playing || !isEnabled() || _incoming != null) return;
    final nextIndex = _nextTrack();
    final src = _sources[nextIndex];
    if (src == null) return;
    try {
      final h = _soloud.play(src, volume: 0, looping: false);
      _incoming = h;
      _incomingIndex = nextIndex;
      _fade(h, _targetVolume, _crossfade);
      if (_active != null) _fade(_active!, 0, _crossfade);
    } catch (_) {
      _incoming = null;
      return;
    }
    _crossfadeTimer?.cancel();
    _crossfadeTimer = Timer(_crossfade, _finishCrossfade);
  }

  void _finishCrossfade() {
    final outgoing = _active;
    _active = _incoming;
    _activeIndex = _incomingIndex;
    _incoming = null;
    _incomingIndex = -1;
    if (outgoing != null) {
      try {
        _soloud.stop(outgoing);
      } catch (_) {}
    }
    final src = _sources[_activeIndex];
    if (src != null) _scheduleCrossfade(src);
  }

  /// Briefly dips the bed under the success fanfare, then restores it.
  void duck({Duration hold = const Duration(milliseconds: 2000)}) {
    if (!_ready || !_playing || !isEnabled() || _active == null) return;
    _fade(_active!, _duckVolume, const Duration(milliseconds: 250));
    _duckTimer?.cancel();
    _duckTimer = Timer(hold, () {
      if (_playing && isEnabled() && _active != null) {
        _fade(_active!, _targetVolume, const Duration(milliseconds: 1200));
      }
    });
  }

  /// Applies the Settings toggle immediately. Turning music back on RESUMES the
  /// current track from where it paused (not a fresh track), so toggling feels
  /// continuous rather than restarting the playlist.
  Future<void> setEnabled(bool on) async {
    if (!_ready) return;
    if (on) {
      if (!_started) {
        ensureStarted();
      } else if (!_playing) {
        _resumeCurrent();
      } else if (_active != null) {
        _fade(_active!, _targetVolume, const Duration(milliseconds: 300));
      }
    } else {
      _crossfadeTimer?.cancel();
      _fadeOutThenPause(const Duration(milliseconds: 300));
      _playing = false;
    }
  }

  /// Resumes the CURRENT track (toggle back on, or returning from background)
  /// and re-arms the crossfade from the live position — so the music continues
  /// instead of restarting from a new track.
  void _resumeCurrent() {
    _playing = true;
    _pauseTimer?.cancel();
    try {
      if (_active != null) _soloud.setPause(_active!, false);
      if (_incoming != null) _soloud.setPause(_incoming!, false);
    } catch (_) {
      // A voice was reclaimed while we were away: start fresh rather than stay
      // silent.
      _started = false;
      _incoming = null;
      ensureStarted();
      return;
    }
    if (_active != null) {
      _fade(_active!, _targetVolume, const Duration(milliseconds: 600));
    }
    _rearmCrossfadeFromPosition();
  }

  /// Re-schedules the crossfade based on the active voice's CURRENT position,
  /// used after a pause/resume cancelled the original one-shot timer.
  void _rearmCrossfadeFromPosition() {
    if (_incoming != null) return; // a crossfade is already in flight
    final src = _sources[_activeIndex];
    if (src == null || _active == null) return;
    final total = _safeLength(src);
    Duration pos;
    try {
      pos = _soloud.getPosition(_active!);
    } catch (_) {
      pos = Duration.zero;
    }
    var lead = total - _crossfade - pos;
    if (lead < const Duration(milliseconds: 300)) {
      lead = const Duration(milliseconds: 300);
    }
    _crossfadeTimer?.cancel();
    _crossfadeTimer = Timer(lead, _beginCrossfade);
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (!_ready) return;
    if (state == AppLifecycleState.resumed) {
      if (_started && _playing && isEnabled()) _resumeCurrent();
    } else {
      // Backgrounded / call / full-screen ad: fade out smoothly before pausing
      // so the bed never gets chopped mid-note. _playing stays true so resume
      // knows to continue; the crossfade timer is re-armed from the live
      // position on resume.
      _crossfadeTimer?.cancel();
      _fadeOutThenPause(const Duration(milliseconds: 220));
    }
  }

  /// Fades both voices to silence over [d], then pauses them once the fade has
  /// finished (so the pause never clips a still-sounding voice).
  void _fadeOutThenPause(Duration d) {
    if (_active != null) _fade(_active!, 0, d);
    if (_incoming != null) _fade(_incoming!, 0, d);
    _pauseTimer?.cancel();
    _pauseTimer = Timer(d, () {
      try {
        if (_active != null) _soloud.setPause(_active!, true);
        if (_incoming != null) _soloud.setPause(_incoming!, true);
      } catch (_) {}
    });
  }

  /// The track's real length, falling back to [_fallbackDuration] when the
  /// decoder can't report one (e.g. a streaming source mid-open).
  Duration _safeLength(AudioSource src) {
    Duration total;
    try {
      total = _soloud.getLength(src);
    } catch (_) {
      total = _fallbackDuration;
    }
    if (total <= const Duration(seconds: 2)) total = _fallbackDuration;
    return total;
  }

  void _fade(SoundHandle handle, double target, Duration d) {
    try {
      _soloud.fadeVolume(handle, target.clamp(0.0, 1.0), d);
    } catch (_) {
      // An invalid/finished handle: nothing to fade.
    }
  }

  void dispose() {
    // Symmetric with the addObserver in main.dart: drop the lifecycle hook so a
    // disposed service can never get a didChangeAppLifecycleState callback and
    // touch already-torn-down voices. No-op if it was never registered.
    WidgetsBinding.instance.removeObserver(this);
    _crossfadeTimer?.cancel();
    _duckTimer?.cancel();
    _pauseTimer?.cancel();
    for (final src in _sources.values) {
      unawaited(_soloud.disposeSource(src).catchError((_) {}));
    }
    _sources.clear();
  }
}
