import 'dart:async';
import 'dart:math';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/widgets.dart';

/// Looping ambient background music as a SHUFFLED, CROSSFADING playlist of
/// several short beds (assets/audio/music_calm_*.wav, generated by
/// tool/generate_music.py).
///
/// Why a playlist with crossfades: a single looping track made the silence at
/// the wrap audible ("it waits, then comes back"). Instead we keep two players
/// (A/B), shuffle the tracks so each plays once before any repeat, and a few
/// seconds before the active track ends we fade it down while fading the next
/// up on the other player — so the music never falls silent and never loops
/// audibly.
///
/// Starts after launch — or on the first tap where autoplay is restricted
/// (web) — pauses with the app lifecycle, and is gated by the user's
/// "Music" setting. Registered as a [WidgetsBindingObserver] in main().
class MusicService with WidgetsBindingObserver {
  MusicService({required this.isEnabled});

  final bool Function() isEnabled;

  /// The shuffled-once-through playlist of bed assets.
  static const List<String> _tracks = [
    'audio/music_calm_1.ogg',
    'audio/music_calm_2.ogg',
    'audio/music_calm_3.ogg',
    'audio/music_calm_4.ogg',
    'audio/music_calm_5.ogg',
    'audio/music_calm_6.ogg',
  ];

  /// How long one track overlaps the next. Both tracks resolve to silence at
  /// their edges, so the overlap is a true crossfade, not a duck.
  static const Duration _crossfade = Duration(milliseconds: 5000);

  /// Begin the crossfade this long before a track's end. Kept equal to the
  /// crossfade length so the outgoing track finishes fading out right as it
  /// reaches its own silent tail.
  static const Duration _crossfadeLead = _crossfade;

  /// Used only if a track's real duration can't be read from the decoder
  /// (rare). Shorter than the shortest generated track (72 s) so we always
  /// start the crossfade before the track ends rather than after.
  static const Duration _fallbackDuration = Duration(seconds: 66);

  /// The bed's base level at full user volume; the mastered tracks are
  /// normalized to ~0.80 (on par with the UI sounds), so full player volume
  /// gives a present bed, not a whisper.
  static const double _baseVolume = 1.0;

  /// Fraction of the playing level the bed dips to under the success fanfare.
  /// Deliberately not near-zero: the fanfare rides *over* the bed.
  static const double _duckFactor = 0.38;

  /// 0..1 user multiplier from settings (musicVolume).
  double _userVolume = 0.70;

  double get _targetVolume => _baseVolume * _userVolume;
  double get _duckVolume => _targetVolume * _duckFactor;

  final List<AudioPlayer> _players = [];

  /// Index (0/1) of the player carrying the foreground track.
  int _active = 0;

  /// The current master level, ramped for fade in/out and ducking. The two
  /// players' actual volumes are derived from this and the crossfade progress.
  double _master = 0;

  /// 0 = entirely on the active player; advances to 1 as the next track fades
  /// in on the other player, then resets when they swap.
  double _xfade = 0;

  /// Shuffle bag: track indices not yet played this cycle (no repeat until all
  /// have played, then it reshuffles).
  final List<int> _bag = [];
  final Random _rng = Random();

  bool _ready = false;
  bool _started = false; // a track has been loaded on the active player
  bool _playing = false; // currently sounding (not paused by toggle/lifecycle)

  Timer? _masterFade;
  Timer? _crossfadeTimer; // schedules the START of the next crossfade
  Timer? _xfadeRamp; // runs the crossfade volume ramp
  StreamSubscription<void>? _completeSubA;
  StreamSubscription<void>? _completeSubB;

  AudioPlayer get _activePlayer => _players[_active];
  AudioPlayer get _idlePlayer => _players[1 - _active];

  /// Applies the user's music-volume preference (0..1). Fades smoothly to the
  /// new level if the bed is currently playing.
  void setUserVolume(double value) {
    _userVolume = value.clamp(0.0, 1.0);
    if (_playing && isEnabled()) {
      _fadeMasterTo(_targetVolume, duration: const Duration(milliseconds: 280));
    }
  }

  Future<void> initialize() async {
    try {
      for (var i = 0; i < 2; i++) {
        final p = AudioPlayer();
        // A long bed, not a UI blip: the media-player path suits it. We manage
        // transitions ourselves, so each player STOPS at its end (no per-player
        // loop) — the playlist provides continuity instead.
        await p.setPlayerMode(PlayerMode.mediaPlayer);
        await p.setReleaseMode(ReleaseMode.stop);
        await p.setVolume(0);
        _players.add(p);
      }
      // Defensive: if a track ends before its scheduled crossfade (timing
      // drift on some decoders), advance immediately so we never go silent.
      _completeSubA = _players[0].onPlayerComplete.listen((_) {
        if (_active == 0) _onTrackEndedEarly();
      });
      _completeSubB = _players[1].onPlayerComplete.listen((_) {
        if (_active == 1) _onTrackEndedEarly();
      });
      _ready = true;
    } catch (_) {
      // Audio is never worth crashing over (emulators without audio,
      // restricted web contexts...): stay silent instead.
      _ready = false;
    }
  }

  /// Next track index from the shuffle bag, refilling (and avoiding an
  /// immediate repeat across cycles) when it empties.
  int _nextTrack() {
    if (_bag.isEmpty) {
      final last = _lastPlayed;
      _bag.addAll(List.generate(_tracks.length, (i) => i));
      _bag.shuffle(_rng);
      // Avoid the same track straddling the cycle boundary.
      if (_bag.length > 1 && _bag.first == last) {
        _bag.add(_bag.removeAt(0));
      }
    }
    final idx = _bag.removeAt(0);
    _lastPlayed = idx;
    return idx;
  }

  int _lastPlayed = -1;

  /// Starts the playlist if it should play and isn't playing yet. Safe to call
  /// often: browsers reject autoplay until the first user gesture, so the app
  /// retries from a global tap listener until one attempt sticks; every later
  /// call is a no-op.
  void ensureStarted() {
    if (!_ready || _started || _players.isEmpty || !isEnabled()) return;
    _started = true;
    _playing = true; // optimistic; reverted if the play attempt is rejected
    unawaited(_startActive(_nextTrack()));
  }

  Future<void> _startActive(int trackIndex) async {
    final p = _activePlayer;
    _xfade = 0;
    try {
      await p.stop();
      await p.setReleaseMode(ReleaseMode.stop);
      await p.setSource(AssetSource(_tracks[trackIndex]));
      await p.setVolume(0);
      await p.resume();
    } catch (_) {
      _playing = false;
      _started = false;
      return;
    }
    _fadeMasterTo(_targetVolume);
    await _scheduleCrossfade(p);
  }

  /// Resumes the CURRENT track from where it was paused (toggle back on, or
  /// returning from background) and re-arms the crossfade from the live
  /// position — so the music continues instead of restarting from a new track.
  Future<void> _resumeCurrent() async {
    _playing = true;
    try {
      await _activePlayer.resume();
      if (_xfade > 0) await _idlePlayer.resume(); // mid-crossfade
    } catch (_) {
      return;
    }
    _fadeMasterTo(_targetVolume, duration: const Duration(milliseconds: 600));
    await _rearmCrossfadeFromPosition(_activePlayer);
  }

  /// Re-schedules the crossfade based on the player's CURRENT position, used
  /// after a pause/resume cancelled the original one-shot timer.
  Future<void> _rearmCrossfadeFromPosition(AudioPlayer p) async {
    if (_xfade > 0) return; // a crossfade is already in flight
    _crossfadeTimer?.cancel();
    Duration total, pos;
    try {
      total = await p.getDuration() ?? _fallbackDuration;
      pos = await p.getCurrentPosition() ?? Duration.zero;
    } catch (_) {
      total = _fallbackDuration;
      pos = Duration.zero;
    }
    var lead = total - _crossfadeLead - pos;
    if (lead < const Duration(milliseconds: 300)) {
      lead = const Duration(milliseconds: 300);
    }
    _crossfadeTimer = Timer(lead, _beginCrossfade);
  }

  /// Reads the active track's real length and arms the timer that begins the
  /// crossfade [_crossfadeLead] before it ends.
  Future<void> _scheduleCrossfade(AudioPlayer p) async {
    _crossfadeTimer?.cancel();
    Duration total;
    try {
      total = await p.getDuration() ?? _fallbackDuration;
    } catch (_) {
      total = _fallbackDuration;
    }
    var lead = total - _crossfadeLead;
    if (lead < const Duration(seconds: 1)) lead = const Duration(seconds: 1);
    _crossfadeTimer = Timer(lead, _beginCrossfade);
  }

  void _onTrackEndedEarly() {
    if (!_playing || !isEnabled()) return;
    // Already crossfading? Let it finish. Otherwise jump straight to the next.
    if (_xfadeRamp?.isActive ?? false) return;
    _beginCrossfade();
  }

  /// Loads the next track on the idle player and ramps the mix from the active
  /// player to it over [_crossfade].
  void _beginCrossfade() {
    if (!_ready || !_playing || !isEnabled()) return;
    if (_xfadeRamp?.isActive ?? false) return;
    final incoming = _idlePlayer;
    final trackIndex = _nextTrack();

    unawaited(() async {
      try {
        await incoming.stop();
        await incoming.setReleaseMode(ReleaseMode.stop);
        await incoming.setSource(AssetSource(_tracks[trackIndex]));
        await incoming.setVolume(0);
        await incoming.resume();
      } catch (_) {
        return;
      }
      _runXfadeRamp();
    }());
  }

  void _runXfadeRamp() {
    _xfadeRamp?.cancel();
    const stepMs = 16;
    final steps = (_crossfade.inMilliseconds / stepMs).ceil().clamp(1, 100000);
    var i = 0;
    _xfadeRamp = Timer.periodic(const Duration(milliseconds: stepMs), (t) {
      i++;
      _xfade = (i / steps).clamp(0.0, 1.0);
      _applyGains();
      if (i >= steps) {
        t.cancel();
        _finishCrossfade();
      }
    });
  }

  Future<void> _finishCrossfade() async {
    final outgoing = _activePlayer;
    _active = 1 - _active; // the incoming player is now the foreground track
    _xfade = 0;
    _applyGains();
    try {
      await outgoing.stop();
    } catch (_) {}
    await _scheduleCrossfade(_activePlayer);
  }

  /// Pushes the current master level onto both players, split by the crossfade
  /// progress. Reads live state each call so a duck or volume change mid-fade
  /// adapts automatically.
  void _applyGains() {
    if (_players.length < 2) return;
    final act = _master * (1 - _xfade);
    final inc = _master * _xfade;
    unawaited(_activePlayer.setVolume(act.clamp(0.0, 1.0)).catchError((_) {}));
    unawaited(_idlePlayer.setVolume(inc.clamp(0.0, 1.0)).catchError((_) {}));
  }

  /// Briefly dips the bed under the success fanfare, then restores it.
  void duck({Duration hold = const Duration(milliseconds: 2000)}) {
    if (!_ready || _players.isEmpty || !_playing || !isEnabled()) return;
    _fadeMasterTo(_duckVolume, duration: const Duration(milliseconds: 250));
    Timer(hold, () {
      if (_playing && isEnabled()) _fadeMasterTo(_targetVolume);
    });
  }

  /// Applies the Settings toggle immediately. Turning music back on RESUMES the
  /// same track from where it paused (not a fresh track), so toggling feels
  /// continuous rather than restarting the playlist.
  Future<void> setEnabled(bool on) async {
    if (!_ready || _players.isEmpty) return;
    if (on) {
      if (!_started) {
        ensureStarted();
      } else if (!_playing) {
        unawaited(_resumeCurrent());
      } else {
        _fadeMasterTo(_targetVolume);
      }
    } else {
      _fadeMasterTo(
        0,
        duration: const Duration(milliseconds: 300),
        onDone: () {
          _playing = false;
          _crossfadeTimer?.cancel();
          _xfadeRamp?.cancel();
          for (final p in _players) {
            unawaited(p.pause().catchError((_) {}));
          }
        },
      );
    }
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (!_ready || _players.isEmpty) return;
    if (state == AppLifecycleState.resumed) {
      // Resume the SAME track from its position and re-arm the crossfade — no
      // restart-from-scratch when the app comes back to the foreground.
      if (_started && _playing && isEnabled()) {
        unawaited(_resumeCurrent());
      }
    } else {
      // Backgrounded / call / full-screen ad: fade out smoothly before pausing
      // so the bed never gets chopped mid-note. The crossfade timer is cancelled
      // and re-armed from the live position on resume.
      _crossfadeTimer?.cancel();
      _fadeMasterTo(
        0,
        duration: const Duration(milliseconds: 220),
        onDone: () {
          for (final p in _players) {
            unawaited(p.pause().catchError((_) {}));
          }
        },
      );
    }
  }

  /// Ramps the master level (and therefore both players, via [_applyGains])
  /// with a smoothstep curve so quick fades never "zipper".
  void _fadeMasterTo(
    double target, {
    Duration duration = const Duration(milliseconds: 1200),
    VoidCallback? onDone,
  }) {
    _masterFade?.cancel();
    if (_players.isEmpty) return;
    const stepMs = 16;
    final steps = (duration.inMilliseconds / stepMs).ceil().clamp(1, 100000);
    final start = _master;
    var i = 0;
    _masterFade = Timer.periodic(const Duration(milliseconds: stepMs), (t) {
      i++;
      final x = (i / steps).clamp(0.0, 1.0);
      final eased = x * x * (3 - 2 * x); // smoothstep
      _master = (start + (target - start) * eased).clamp(0.0, 1.0);
      _applyGains();
      if (i >= steps) {
        t.cancel();
        onDone?.call();
      }
    });
  }

  void dispose() {
    _masterFade?.cancel();
    _crossfadeTimer?.cancel();
    _xfadeRamp?.cancel();
    unawaited(_completeSubA?.cancel());
    unawaited(_completeSubB?.cancel());
    for (final p in _players) {
      p.dispose();
    }
  }
}
