import 'dart:async';

import 'package:flutter_soloud/flutter_soloud.dart';

import 'audio_taper.dart';

/// Short procedural sound effects (assets/audio, generated by
/// tool/generate_sounds.py). All playback is fire-and-forget and gated by
/// the user's "Sound effects" setting.
///
/// Backed by **SoLoud** (`flutter_soloud`): every cue is decoded into memory
/// once at startup, and each play spawns a FRESH voice that SoLoud mixes
/// alongside any still-ringing ones. This is the fix for the persistent
/// "tık/crackle": the old `audioplayers` path retriggered a sound by
/// `stop()`/`seek(0)`-ing a player that might still be sounding, and that hard
/// discontinuity is exactly what clicked. With per-play voices there is never a
/// tail to cut — overlapping copies simply ring out on their own.
class SoundService {
  SoundService({required this.isEnabled});

  final bool Function() isEnabled;

  // Lazily resolved so merely CONSTRUCTING the service never loads SoLoud's
  // native library — that lets the test fakes (which extend this class but never
  // call initialize) run in the plain Dart VM, where the .so isn't present.
  late final SoLoud _soloud = SoLoud.instance;

  /// Each effect decoded into memory once, keyed by asset filename.
  final Map<String, AudioSource> _sources = {};

  bool _ready = false;

  /// 0..1 user multiplier (soundVolume from settings), perceptually tapered.
  /// Applied per play() — one-shots are fire-and-forget so there is no live
  /// voice to re-scale after the fact.
  double _volume = 1.0;

  /// The discrete cues plus the keyboard tap. All loaded into memory: they are
  /// tiny, and memory voices have the lowest possible retrigger latency.
  static const List<String> _assets = [
    'tap.wav',
    'hint.wav',
    'conflict.wav',
    'success.wav',
    'achievement.wav',
    'word.wav',
  ];

  /// Master output headroom. SoLoud SUMS all voices, so overlapping loud cues
  /// (a ~2 s success fanfare + key taps + the music bed) can sum past full scale
  /// and hard-clip — the reported "patlama". Scaling the whole mix down leaves
  /// room for those overlaps to add cleanly. It is set on the shared engine, so
  /// it is the master headroom for music too (the correct place for it).
  static const double _globalHeadroom = 0.7;

  /// A generous simultaneous-voice cap so a burst never culls a still-playing
  /// cue; with the per-cue throttle below the real count stays well under this.
  static const int _maxVoices = 24;

  /// Long cues that must ring out fully — PROTECTED from voice-culling so a
  /// later tap/cue can never cut the fanfare off mid-play ("yarıda kesilme").
  static const Set<String> _longCues = {'success.wav', 'achievement.wav'};

  /// Minimum gap before the SAME discrete cue retriggers. A wrong-letter spam or
  /// a repeated letter would otherwise spawn a dozen overlapping voices that both
  /// flood the mix (clipping) and hit the voice cap (culling). Distinct cues are
  /// unaffected; the per-keystroke tap is exempt so it tracks every key.
  static const int _minGapMs = 60;
  final Map<String, int> _lastPlayedMs = {};

  /// Applies the user's effect-volume preference. Cheap and idempotent, so
  /// Settings can call it on every change; takes effect on the next cue.
  void setUserVolume(double value) {
    // Perceptual taper (shared with MusicService): loudness is roughly
    // logarithmic, so the raw slider position is reshaped so the on-screen %
    // tracks how loud it actually sounds. 0 -> 0, 1 -> 1 stay exact.
    _volume = audioTaper(value);
  }

  Future<void> initialize() async {
    if (_ready) return;
    try {
      // The SoLoud engine is a process-wide singleton shared with MusicService;
      // initialising twice is a no-op, so whichever service runs first wins.
      if (!_soloud.isInitialized) {
        await _soloud.init();
      }
      // Master headroom + a roomy voice cap so overlapping cues neither clip
      // (summed past full scale) nor cull a still-playing fanfare.
      try {
        _soloud.setGlobalVolume(_globalHeadroom);
        _soloud.setMaxActiveVoiceCount(_maxVoices);
      } catch (_) {}
      for (final name in _assets) {
        _sources[name] = await _soloud.loadAsset(
          'assets/audio/$name',
          mode: LoadMode.memory,
        );
      }
      _ready = true;
    } catch (_) {
      // Audio is never worth crashing over (emulators without audio, a web
      // build without the SoLoud worker, restricted contexts...): stay silent.
      _ready = false;
    }
  }

  /// Spawns a fresh voice for [key]. SoLoud mixes it with any still-ringing
  /// copies, so a rapid retrigger never stops/seeks a live voice (the old click
  /// source). The voice frees itself when it finishes. Discrete cues are
  /// throttled (see [_minGapMs]); long cues are protected from culling.
  void _play(String key, {bool throttle = true}) {
    if (!_ready || !isEnabled()) return;
    final source = _sources[key];
    if (source == null) return;
    if (throttle) {
      final now = DateTime.now().millisecondsSinceEpoch;
      final last = _lastPlayedMs[key];
      if (last != null && now - last < _minGapMs) return;
      _lastPlayedMs[key] = now;
    }
    try {
      final handle = _soloud.play(source, volume: _volume);
      // Keep the long fanfares alive against a later burst of cues.
      if (_longCues.contains(key)) _soloud.setProtectVoice(handle, true);
    } catch (_) {
      // A single failed cue must never surface to the player.
    }
  }

  // The per-keystroke tap must track every key, so it is exempt from the
  // throttle; it is the quietest cue, so un-throttled overlap can't clip.
  void tap() => _play('tap.wav', throttle: false);

  void hint() => _play('hint.wav');

  void conflict() => _play('conflict.wav');

  /// A single soft bell when a typed guess finishes a whole word.
  void wordComplete() => _play('word.wav');

  void success() => _play('success.wav');

  void achievement() => _play('achievement.wav');

  void dispose() {
    // Only OUR sources — never deinit the shared engine (MusicService may still
    // be using it) and never disposeAllSources (that would take the music beds).
    for (final source in _sources.values) {
      unawaited(_soloud.disposeSource(source).catchError((_) {}));
    }
    _sources.clear();
    _ready = false;
  }
}
