import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter_soloud/flutter_soloud.dart';

import 'audio_taper.dart';

/// Short procedural sound effects (assets/audio, generated by
/// tool/generate_sounds.py). All playback is fire-and-forget and gated by
/// the user's "Sound effects" setting.
///
/// Backed by **SoLoud** (`flutter_soloud`): every cue is decoded into memory
/// once at startup, and each play spawns a FRESH voice that SoLoud mixes
/// alongside any still-ringing ones. This is the fix for the persistent
/// "tık/crackle": the old `audioplayers` path retriggered a sound by
/// `stop()`/`seek(0)`-ing a player that might still be sounding, and that hard
/// discontinuity is exactly what clicked. With per-play voices there is never a
/// tail to cut — overlapping copies simply ring out on their own.
class SoundService {
  SoundService({required this.isEnabled});

  final bool Function() isEnabled;

  // Lazily resolved so merely CONSTRUCTING the service never loads SoLoud's
  // native library — that lets the test fakes (which extend this class but never
  // call initialize) run in the plain Dart VM, where the .so isn't present.
  late final SoLoud _soloud = SoLoud.instance;

  /// Each effect decoded into memory once, keyed by asset filename.
  final Map<String, AudioSource> _sources = {};

  bool _ready = false;
  bool _initRetrying = false;

  /// Self-heals a failed/cold engine: if a cue is requested while not ready
  /// (e.g. the one-shot startup init lost the audio device), kick a single
  /// re-init in the background so the NEXT cue works instead of staying silent
  /// forever (which read as "the sound settings do nothing"). Guarded so only
  /// one retry is ever in flight.
  void _ensureReady() {
    if (_ready || _initRetrying) return;
    _initRetrying = true;
    initialize().whenComplete(() => _initRetrying = false);
  }

  /// 0..1 user multiplier (soundVolume from settings), perceptually tapered.
  /// Applied per play() — one-shots are fire-and-forget so there is no live
  /// voice to re-scale after the fact.
  double _volume = 1.0;

  /// The discrete cues plus the keyboard tap. All loaded into memory: they are
  /// tiny, and memory voices have the lowest possible retrigger latency.
  static const List<String> _assets = [
    'tap.wav',
    'hint.wav',
    'conflict.wav',
    'success.wav',
    'achievement.wav',
    'word.wav',
  ];

  /// Master output headroom. SoLoud SUMS all voices, so overlapping loud cues
  /// (a ~2 s success fanfare + key taps + the music bed) can sum past full scale
  /// and hard-clip — the reported "patlama". Scaling the whole mix down leaves
  /// room for those overlaps to add cleanly. It is set on the shared engine, so
  /// it is the master headroom for music too (the correct place for it).
  static const double _globalHeadroom = 0.7;

  /// A generous simultaneous-voice cap so a burst never culls a still-playing
  /// cue; with the per-cue throttle below the real count stays well under this.
  static const int _maxVoices = 24;

  /// Every discrete cue is PROTECTED from voice-culling so pressure on the
  /// voice pool (typing bursts, music crossfades) can never cut a still-ringing
  /// bell off mid-play ("yarıda kesilme"). Previously only the two fanfares
  /// were protected and the word/hint/conflict bells could be culled exactly
  /// when the player was most active. Only the per-keystroke tap stays
  /// unprotected — it is 55 ms long and the correct victim under pressure.
  @visibleForTesting
  static const Set<String> protectedCues = {
    'success.wav',
    'achievement.wav',
    'word.wav',
    'hint.wav',
    'conflict.wav',
  };

  /// The keystroke tap is the one cue allowed to pile up (one per key press),
  /// so it gets its own small concurrency cap: beyond this many live tap
  /// voices the OLDEST tap is stopped — a 55 ms thock is never missed, and tap
  /// floods (hold-to-repeat, ghost touches) can never pressure the voice pool
  /// toward culling territory.
  @visibleForTesting
  static const int maxConcurrentTaps = 8;
  final List<SoundHandle> _tapHandles = [];

  /// Minimum gap before the SAME discrete cue retriggers. A wrong-letter spam or
  /// a repeated letter would otherwise spawn a dozen overlapping voices that both
  /// flood the mix (clipping) and hit the voice cap (culling). Distinct cues are
  /// unaffected. Exempt: the per-keystroke tap (tracks every key) and the
  /// word-complete bell — completing two words with two fast keystrokes is two
  /// real achievements, and dropping the second bell read as a broken cue.
  static const int _minGapMs = 60;
  final Map<String, int> _lastPlayedMs = {};

  /// Applies the user's effect-volume preference. Cheap and idempotent, so
  /// Settings can call it on every change; takes effect on the next cue.
  void setUserVolume(double value) {
    // Perceptual taper (shared with MusicService): loudness is roughly
    // logarithmic, so the raw slider position is reshaped so the on-screen %
    // tracks how loud it actually sounds. 0 -> 0, 1 -> 1 stay exact.
    _volume = audioTaper(value);
  }

  Future<void> initialize() async {
    // NO audio engine on web. SoLoud's web backend needs an AudioWorklet +
    // SharedArrayBuffer, which requires COOP/COEP headers GitHub Pages cannot
    // send — initialising it there WEDGES the main thread right after the
    // first frame (reproduced in a real Chromium: first frame at ~14s, then
    // the renderer blocks forever — the live preview's "stuck on loading").
    // The web preview is deliberately a silent demo, like ads/purchases.
    if (kIsWeb) return;
    if (_ready) return;
    try {
      // The SoLoud engine is a process-wide singleton shared with MusicService;
      // initialising twice is a no-op, so whichever service runs first wins.
      if (!_soloud.isInitialized) {
        await _soloud.init();
      }
      // Master headroom + a roomy voice cap so overlapping cues neither clip
      // (summed past full scale) nor cull a still-playing fanfare.
      try {
        _soloud.setGlobalVolume(_globalHeadroom);
        _soloud.setMaxActiveVoiceCount(_maxVoices);
      } catch (_) {}
      for (final name in _assets) {
        _sources[name] = await _soloud.loadAsset(
          'assets/audio/$name',
          mode: LoadMode.memory,
        );
      }
      _ready = true;
    } catch (_) {
      // Audio is never worth crashing over (emulators without audio, a web
      // build without the SoLoud worker, restricted contexts...): stay silent.
      _ready = false;
    }
  }

  /// Spawns a fresh voice for [key]. SoLoud mixes it with any still-ringing
  /// copies, so a rapid retrigger never stops/seeks a live voice (the old click
  /// source). The voice frees itself when it finishes. Discrete cues are
  /// throttled (see [_minGapMs]); long cues are protected from culling.
  void _play(String key, {bool throttle = true}) {
    if (kIsWeb) return; // silent web preview; see initialize()
    if (!isEnabled()) return;
    if (!_ready) {
      _ensureReady(); // self-heal for the next cue; this one stays silent
      return;
    }
    // The OS can tear the shared engine down while backgrounded; _ready would
    // then lie and every play() would fail silently forever (the reported
    // "no sound after returning to the app"). Detect the dead engine and
    // re-init — the next cue sounds again.
    try {
      if (!_soloud.isInitialized) {
        _ready = false;
        _sources.clear();
        _ensureReady();
        return;
      }
    } catch (_) {}
    final source = _sources[key];
    if (source == null) return;
    if (throttle) {
      final now = DateTime.now().millisecondsSinceEpoch;
      final last = _lastPlayedMs[key];
      if (last != null && now - last < _minGapMs) return;
      _lastPlayedMs[key] = now;
    }
    try {
      final handle = _soloud.play(source, volume: _volume);
      // Keep every meaningful cue alive against a later burst of voices —
      // only the disposable keystroke tap may ever be culled.
      if (protectedCues.contains(key)) {
        _soloud.setProtectVoice(handle, true);
      } else if (key == 'tap.wav') {
        _capTapVoices(handle);
      }
    } catch (_) {
      // A single failed cue must never surface to the player.
    }
  }

  /// Tracks live tap voices and stops the OLDEST once more than
  /// [maxConcurrentTaps] ring at once. Finished handles are pruned first, so
  /// normal typing never triggers a stop — only a genuine flood does.
  void _capTapVoices(SoundHandle handle) {
    _tapHandles.add(handle);
    try {
      _tapHandles.removeWhere((h) => !_soloud.getIsValidVoiceHandle(h));
      while (_tapHandles.length > maxConcurrentTaps) {
        final oldest = _tapHandles.removeAt(0);
        _soloud.stop(oldest);
      }
    } catch (_) {
      // Bookkeeping only — a failure here must never mute the tap itself.
      if (_tapHandles.length > maxConcurrentTaps * 4) _tapHandles.clear();
    }
  }

  // The per-keystroke tap must track every key, so it is exempt from the
  // throttle; it is the quietest cue, so un-throttled overlap can't clip.
  void tap() => _play('tap.wav', throttle: false);

  void hint() => _play('hint.wav');

  void conflict() => _play('conflict.wav');

  /// A single soft bell when a typed guess finishes a whole word. Exempt from
  /// the same-cue throttle: two words finished by two fast keystrokes are two
  /// real events, and swallowing the second bell read as a broken cue.
  void wordComplete() => _play('word.wav', throttle: false);

  void success() => _play('success.wav');

  void achievement() => _play('achievement.wav');

  void dispose() {
    // Only OUR sources — never deinit the shared engine (MusicService may still
    // be using it) and never disposeAllSources (that would take the music beds).
    for (final source in _sources.values) {
      unawaited(_soloud.disposeSource(source).catchError((_) {}));
    }
    _sources.clear();
    _tapHandles.clear();
    _ready = false;
  }
}
