import 'dart:async';

import 'package:flutter_soloud/flutter_soloud.dart';

import 'audio_taper.dart';

/// Short procedural sound effects (assets/audio, generated by
/// tool/generate_sounds.py). All playback is fire-and-forget and gated by
/// the user's "Sound effects" setting.
///
/// Backed by **SoLoud** (`flutter_soloud`): every cue is decoded into memory
/// once at startup, and each play spawns a FRESH voice that SoLoud mixes
/// alongside any still-ringing ones. This is the fix for the persistent
/// "tık/crackle": the old `audioplayers` path retriggered a sound by
/// `stop()`/`seek(0)`-ing a player that might still be sounding, and that hard
/// discontinuity is exactly what clicked. With per-play voices there is never a
/// tail to cut — overlapping copies simply ring out on their own.
class SoundService {
  SoundService({required this.isEnabled});

  final bool Function() isEnabled;

  // Lazily resolved so merely CONSTRUCTING the service never loads SoLoud's
  // native library — that lets the test fakes (which extend this class but never
  // call initialize) run in the plain Dart VM, where the .so isn't present.
  late final SoLoud _soloud = SoLoud.instance;

  /// Each effect decoded into memory once, keyed by asset filename.
  final Map<String, AudioSource> _sources = {};

  bool _ready = false;

  /// 0..1 user multiplier (soundVolume from settings), perceptually tapered.
  /// Applied per play() — one-shots are fire-and-forget so there is no live
  /// voice to re-scale after the fact.
  double _volume = 1.0;

  /// The discrete cues plus the keyboard tap. All loaded into memory: they are
  /// tiny, and memory voices have the lowest possible retrigger latency.
  static const List<String> _assets = [
    'tap.wav',
    'hint.wav',
    'conflict.wav',
    'success.wav',
    'achievement.wav',
    'word.wav',
  ];

  /// Applies the user's effect-volume preference. Cheap and idempotent, so
  /// Settings can call it on every change; takes effect on the next cue.
  void setUserVolume(double value) {
    // Perceptual taper (shared with MusicService): loudness is roughly
    // logarithmic, so the raw slider position is reshaped so the on-screen %
    // tracks how loud it actually sounds. 0 -> 0, 1 -> 1 stay exact.
    _volume = audioTaper(value);
  }

  Future<void> initialize() async {
    if (_ready) return;
    try {
      // The SoLoud engine is a process-wide singleton shared with MusicService;
      // initialising twice is a no-op, so whichever service runs first wins.
      if (!_soloud.isInitialized) {
        await _soloud.init();
      }
      for (final name in _assets) {
        _sources[name] = await _soloud.loadAsset(
          'assets/audio/$name',
          mode: LoadMode.memory,
        );
      }
      _ready = true;
    } catch (_) {
      // Audio is never worth crashing over (emulators without audio, a web
      // build without the SoLoud worker, restricted contexts...): stay silent.
      _ready = false;
    }
  }

  /// Spawns a fresh voice for [key]. SoLoud mixes it with any still-ringing
  /// copies, so a rapid retrigger never stops/seeks a live voice (the old click
  /// source). The voice frees itself when it finishes.
  void _play(String key) {
    if (!_ready || !isEnabled()) return;
    final source = _sources[key];
    if (source == null) return;
    try {
      _soloud.play(source, volume: _volume);
    } catch (_) {
      // A single failed cue must never surface to the player.
    }
  }

  void tap() => _play('tap.wav');

  void hint() => _play('hint.wav');

  void conflict() => _play('conflict.wav');

  /// A single soft bell when a typed guess finishes a whole word.
  void wordComplete() => _play('word.wav');

  void success() => _play('success.wav');

  void achievement() => _play('achievement.wav');

  void dispose() {
    // Only OUR sources — never deinit the shared engine (MusicService may still
    // be using it) and never disposeAllSources (that would take the music beds).
    for (final source in _sources.values) {
      unawaited(_soloud.disposeSource(source).catchError((_) {}));
    }
    _sources.clear();
    _ready = false;
  }
}
